name: poke-api-nestjs

services:
  redis:
    container_name: poke_redis
    image: redis:alpine3.21
    restart: always
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - poke-network

  psql:
    container_name: poke_db
    image: postgres:16
    restart: always
    ports:
      - "${DATABASE_PORT}:5432"
    environment:
      POSTGRES_DB: "${DATABASE_DB}"
      POSTGRES_USER: "${DATABASE_USER}"
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER}"]
      interval: 5s
      timeout: 3s
      retries: 10
    volumes:
      - psql_data:/var/lib/postgresql/data
    networks:
      - poke-network

  # nest-bun-app:
  #   container_name: poke_app
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   depends_on:
  #     mysql:
  #       condition: service_healthy
  #     redis:
  #       condition: service_healthy
  #   env_file:
  #     - .env.docker
  #   ports:
  #     - "${PORT}:${PORT}"
  #   restart: unless-stopped
  #   networks:
  #     - poke-network

networks:
  poke-network:
    driver: bridge

volumes:
  psql_data:
